Developer console
javascript-tutorial/hy.javascript.info pull request #70
Opened 2021-02-28 13:46 UTC by ArthurHakobyan

I translate the section devtools. the title of that article is Developer console. please review the translation and let me know.

2021-02-28 17:46 UTC, bugron commented
@ArthurHakobyan [AUTHORING.md](https://github.com/javascript-tutorial/hy.javascript.info/blob/master/AUTHORING.md#internal-links) has some notes about those links you mentioned.

2021-02-28 18:28 UTC, bugron requested changes
Խնդրում եմ ուշադիր լինել կետադրական սխալներին, ավելորդ բացատներին, վերջակետերին: Ինչպես նաև տեղեր կան, որտեղ բացատները բացակայում են, բայց անհրաժեշտ են:

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Կոդը հակված է սխալվելու: Դուք ամենայն հավանականությամբ թույլ կտաք սխալներ ... Oh, ինչի՞ մասին եմ խոսում: Դուք « բացարձակապես » սխալներ եք գործելու,  եթե դուք իհարկե մարդ եք, ոչ թե [ռոբոտ](https://en.
Ստորև բերում եմ այս նախադասության թարգմանության առաջարկվող տարբերակը: Փոխել եմ առաջին նախադասությունն ու որոշ կետադրական ուղղումներ արել:

```
Կոդը հակված է պարունակելու սխալներ: Դուք ամենայն հավանականությամբ թույլ կտաք սխալներ... O, ինչի՞ մասին եմ խոսում: Դուք *անպայման* սխալներ եք գործելու, եթե դուք, իհարկե, մարդ եք, ոչ թե [ռոբոտ](https://en.wikipedia.org/wiki/Bender_(Futurama)).
```

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +# Ծրագրավորման բարձակ
Առաջարկում եմ փակագծերում նշել Developer console, որ քանի որ կարդացողը առաջին անգամ է հանդիպելու այս թարգմանությանը մեր տեքտում ու առաջին հայացքից կարող է անհասկանալի լինել:

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Բացեք կայքը [bug.html](bug.html).
Ճիշտ տարբերակն է՝ Բացեք [bug.html](bug.html) էջը:
Վերջակետերը պետք է փոխել (անգլերենում՝ կետ, հայերենում՝ : )

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Այնտեղ JavaScript կոդի մեջ սխալ կա: Այն թաքնված է սովորական այցելուի աչքից, ուստի եկեք բացենք ծրագրավորման գործիքները ՝ այն տեսնելու համար:
գործիքները ՝ -> գործիքները՝
Բացատները (space) որոշ տեղերում ավելորդ են:

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +- Այստեղ մենք կարող ենք տեսնել կարմիրով գունավորված սխալի հաղորդագրությունը: Այս դեպքում սցենարը պարունակում է անհայտ «լալալա» հրաման:
Այստեղ lalala-ն թարգմանել պետք չէ:

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +- Աջ կողմում կա աղբյուրի վրա սեղմվող հղում `bug.html:12` գծի համարով, որտեղ սխալը տեղի է ունեցել:
գծի համարով -> տողի համարով

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Սխալ հաղորդագրության տակ կա կապույտ գույնի `>` նշան։ Այն նշում է «հրամանի տողը», որտեղ մենք կարող ենք մուտքագրել JavaScript հրամաններ: Սեղմեք `key:Enter` դրանք գործարկելու համար:
Սխալ հաղորդագրության տակ -> Սխալի հաղորդագրության տակ 
Այն նշում է «հրամանի տողը» -> Այն նշում է այն տողը

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +```smart header="Բազմաtwx մուտք"
Տողի թարգմանությունը ուղղման կարիք ունի:

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Նրանց տեսքը և աշխատանքը բավականին նման է: Երբ իմանաք, թե ինչպես օգտագործել այս գործիքներից մեկը (կարող եք սկսել Chrome- ից), կարող եք հեշտությամբ անցնել մյուսի:
հեշտությամբ անցնել մյուսի -> հեշտությամբ անցնել մյուսին

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Safari (Mac զննիչ, չի աջակցվում Windows / Linux- ի կողմից) այն մի փոքր առանձնահատուկ է: Մենք նախ պետք է միացնենք «ծրագրավորման գործիքները»:
(Mac զննիչ, չի աջակցվում Windows / Linux- ի կողմից) -> (Mac զննիչ, հասանելի չէ Windows և Linux ՕՀ-երում)

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Բացեք Preferences և գնացեք "Advanced" պատուհան. Ներքևում նշման տուփ(checkbox) կա ծրագրավորման գործիքների համար։
1. Բացեք Preferences -> Բացեք Preferences էջը
2. պատուհան. -> պատուհան:
3. Առաջարկում եմ checkbox-ը չթարգմանել: Այս նախագծում ընդունված է նման տերմինները չթարգմանել: Համարում եմ, որ այս դեպքում թարգմանությունն ավելի ընթեռնելի կլինի, եթե checkbox-ը թողնենք ոնց կա:

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Հիմա `key:Cmd+Opt+C` կարող է բաղցել բարձակը(console): Նաև նշենք, որ հայտնվել է «ծրագրավորման գործիքներ» անվանմամբ ընտրացանկի նոր վերին կետը: Այն ունի շատ հրամաններ և տարբերակներ:
բաղցել -> բացել

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +- Դրանք կարելի է բացել `key:F12` Windows-ի համար նախատեսված շատ զննիչներով՝ օրինակ Chrome-ում։ Mac-ի համար պետք է սեղմել `key:Cmd+Opt+J`, Safari: `key:Cmd+Opt+C` (բայց անհրաժեշտ է նախ ակտիվացնել).
շատ զննիչներով -> շատ զննիչներում

2021-02-28 18:28 UTC, bugron commented on 1-js/01-getting-started/4-devtools/article.md
> +Այժմ մենք ունենք պատրաստ միջավայրը:Հաջորդ բաժնում մենք կանդրադառնանք JavaScript- ին:
Այժմ մենք ունենք պատրաստ միջավայրը -> Այժմ մեր միջավայրը պատրաստ է

2021-03-02 09:54 UTC, ArthurHakobyan commented
done

2021-03-02 09:59 UTC, ArthurHakobyan commented
/done

2021-03-02 10:07 UTC, bugron approved these changes
Looks good to me. Great work!

2021-03-02 10:08 UTC, merged