Type Conversions
javascript-tutorial/hy.javascript.info pull request #78
Opened 2021-07-17 18:41 UTC by Arthur-Gyulabyan

Translated article of "Type Conversion" section.

2021-07-19 08:47 UTC, bugron commented
Thanks for the PR. I'll review it today.

2021-07-19 18:16 UTC, bugron commented on 1-js/02-first-steps/07-type-conversions/article.md
> +let age = Number("կամայակն տող, թվի փոխարեն");
```suggestion
let age = Number("կամայական տող, թվի փոխարեն");
```

2021-07-19 18:22 UTC, bugron requested changes
Just a few typos to fix otherwise looks great!

2021-07-19 18:22 UTC, bugron commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Փոխարկումը ենթարկվուվ է հետևյալ կանոններին․
```suggestion
Փոխարկումը ենթարկվում է հետևյալ կանոններին․
```

2021-07-19 18:22 UTC, bugron commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Ենթարկվուվ է հետևյալ կանուններին․
```suggestion
Ենթարկվում է հետևյալ կանուններին․
```

2021-07-20 06:53 UTC, Arthur-Gyulabyan commented
/done

2021-07-20 06:54 UTC, Arthur-Gyulabyan commented
Thanks for the review.

2021-07-20 18:07 UTC, bugron approved these changes
LGTM

2021-07-20 18:07 UTC, merged