11-logical-operators translated
javascript-tutorial/hy.javascript.info pull request #82
Opened 2021-08-09 13:53 UTC by vahmelk99

Please check my translation.

2021-08-09 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/hy.javascript.info?pullRequest=82) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/hy.javascript.info?pullRequest=82) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/hy.javascript.info?pullRequest=82) it.</sub>

2021-08-09 14:02 UTC, bugron commented
Thanks for the PR @vahmelk99. I'll be reviewing it soon.

2021-08-10 06:23 UTC, bugron requested changes
Please do not be discouraged by the number of comments. It is normal for this project. Once the suggested changes are implemented I'll give it another round of reviews. Thanks.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
> +alert(null || 2 || undefined)
Please restore the original formatting of this line.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
> +Կարևորություն: 5
You should not translate lines similar to this one. Please, restore it.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
> +alert(null || 2 || undefined)
Please restore the original formatting of this line.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
> +Կարևորություն: 3
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
> +alert(alert(1) || 2 || alert(3))
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +alert(alert(1) || 2 || alert(3))
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +`alert`֊ի կանչը չի վերադարձնում ոչ մի արժեք։ Կամ այլ կերպա ասած վերադարձնում է `undefined`։
You have a typo in this sentence.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
> +3. Երկրորդ օպերանդը `2` է, որը ճշմարիտ է, և ԿԱՄ֊ը դադարացնում է իր հաշվարկները։ `2`֊ը վերադարձվում է և ցուցադրվում էկրանին դրսի `alert`֊ի միջոցով։
You have a typo in this sentence.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
> +alert(1 && null && 2)
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
> +Կարևորություն: 5
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
> +alert(1 && null && 2)
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
> +alert(alert(1) && alert(2));
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> +Կարևորություն: 3
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> +alert(alert(1) && alert(2))
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
> +Կարևորություն: 5
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
> +Կարևորություն: 3
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
> +Կարևորություն: 3
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/8-if-question/task.md
> +Կարևորություն: 5
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/8-if-question/task.md
> -
Please restore the new line at the end of this file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
> -
Please restore the new line at the end of this file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> -
Please restore the new line at the end of this file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
> -
Please restore the new line at the end of this line.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
> -
Please restore the new line at the end of this file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
> -
Please restore the new line at the end of this file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
> -
Please restore the new line at the end of this file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/9-check-login/ifelse_task.svg
> -<svg xmlns="http://www.w3.org/2000/svg" width="599" height="493" viewBox="0 0 599 493"><defs><style>@import url(https://fonts.googleapis.com/css?family=Open+Sans:bold,italic,bolditalic%7CPT+Mono);@fo
Please restore the original SVG file.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
> +Ուշադրություն դարձրեք ուղղահայաց խորություններին(indents) `if` բլոկների ներսում։ Դրանք պարտադիր չեն, բայց դարձնում են ծրագիրը ավելի ընոեռնելի։
You have a couple of typos here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +Կարևորություն: 3
^

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +Գրեք ծրագիր, որը կպահանջի մուտքի օգտագործելով `prompt`֊ը։
You have a typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/9-check-login/task.md
> +- Դատարի տողի և չեղարկված(cancelled) դեպքերում ցուցադրվում է "Չեղարկված է"
Also a typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +JavaScript-ում կան չորս տրամաբանական օպերատորներ՝ `||` (ԿԱՄ), `&&` (ԵՎ), `!` (ՈՉ), `??` (Null-ի հետ համակցման). Այստեղ մենք կծանոթանանք առաջին երեքին։ `??` օպերատորին կարող եք ծանոթանալ հաջորդ հոդված
```suggestion
JavaScript-ում կան չորս տրամաբանական օպերատորներ՝ `||` (ԿԱՄ), `&&` (ԵՎ), `!` (ՈՉ), `??` (Nullish Coalescing). Այստեղ մենք կծանոթանանք առաջին երեքին։ `??` օպերատորին կարող եք ծանոթանալ հաջորդ հոդվածում։
```
I'd prefer to go with the original name of this operator or at least also supply the English original name.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Չնայած նրանք անվանվում են "տրամաբանական", նրանք կարող են կիրառվել կամայական(տարբերվող տրամաբանական տիպից) տիպի վրա։ Նրանց արդյունքը նույպես կարող է լինել կամայական տիպի։
You have a typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Դասական ծրագրավորման մեջ տրամաբանական ԿԱՄ օպերատորը կիրառվում է միայն տրամաբանական արժեքների վրա։ Եթե նրա արգումենտներից մեկը ճշմարի `true` է, ապա այն վերադարձնում է `true`, հակառակ դեպքում՝ `false`։
You have a typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert(false || false) // false
Please restore original formatting of those 4 lines.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Ինչպես տեսնում ենք արդյունքը միշտ ճիշտ(`true`) է, բացի այն դեպքից, երբ երկու օպերանդներն էլ սխալ(`false`) են։
Please put spaces before parentheses. @vahmelk99 make sure to check other places too.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +  alert('Ճշմարիտ է!')
Please put the line `// աշխատում է ինչպես if( true || false )` at its original place (the line before) to not introduce a line shift. See English text.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +   Օրինակի, ունենք `firstName`, `lastName` և `nickName` փոփոխականները, բոլորը ըստ ցանկության կարող են ստանալ սխալական կամ `undefined` արժեքներ։
You have a typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +   ```
Please restore original indentation of these lines.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +   ```
Please restore the indentation of these lines.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert(false && false) // false
Restore original formatting of these lines.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +   ԿԱՄ `||`֊ի մեկ այլ հատկությունը այսպես կոչված "կրճատ հաշվարկ"֊ի հատկությունն է։
I can see you removed some white space at the beginning of this and next sentences up to the section `## && (AND)`. Please restore them.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +  // հաշվվում է ինչպես true && false
Please reset the original place of this line.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
>  In other words, AND returns the first falsy value or the last value if none were found.
This line is not translated.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +// Երկրորդ օպերանդը անտեսվում է։
Please do not introduce unnecessary line breaks.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +`````
You have an extra backtick here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Աջ կողմի գործողությունը կկատարվի այն ժամանակ, երբ ձախից աջ արժեքավրումը հասնի իրեն(այսինքն ձախ կողմի բոլոր արժեքները ճշմարիտ են)։ Դա տեղի կունենա, եթե `(x > 0)` արտահայտությունը ճիշտ լինի։
You have a typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +`````
An extra backtick here also.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Օպերատորը ընդունում է մեկ արգումենտ է կատարում հետևյալ քայլերը․
A typo here.

2021-08-10 06:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert(!0) // true
Restore original formatting.

2021-08-10 06:25 UTC, bugron commented
@vahmelk99 also for future PRs the name of the PR should exactly match the title of the article you are translating (see https://github.com/javascript-tutorial/hy.javascript.info/issues/1). For example the title of this PR should have been `Logical operators`.

2021-08-11 18:12 UTC, vahmelk99 commented on 1-js/02-first-steps/11-logical-operators/article.md
> +   ԿԱՄ `||`֊ի մեկ այլ հատկությունը այսպես կոչված "կրճատ հաշվարկ"֊ի հատկությունն է։
That was my auto save formatter :D I'll turn it off in the next translations)

2021-08-11 19:02 UTC, vahmelk99 commented
> @vahmelk99 also for future PRs the name of the PR should exactly match the title of the article you are translating (see #1). For example the title of this PR should have been `Logical operators`.

Should I create a new PR?

2021-08-11 19:59 UTC, bugron commented
@vahmelk99 nope, just have that noted for future PRs. Thanks.

2021-08-11 20:38 UTC, vahmelk99 commented
Please review my translation one more time. Thank you for your time. Hope I don't miss anything) /done

2021-08-11 20:40 UTC, vahmelk99 commented
Please review my translation one more time. Thank you for your time. Hope I don't miss anything) /done

2021-08-11 21:06 UTC, bugron commented
@vahmelk99 it seems that you need to sign the CLA. That's a routine for this project.

2021-08-12 12:49 UTC, vahmelk99 commented
/done

2021-08-12 13:25 UTC, bugron commented
Did you sign the CLA? Because GitHub still shows you didn't.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/13225220/129204576-8cb3909b-99c5-4c71-869d-22b2e8254c58.png">

2021-08-13 07:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
> -
@vahmelk99 did you restore the new line at the end of this file because GitHub does not show it is?

2021-08-13 07:23 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
> -
Same thing with the new line here.

2021-08-13 07:25 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
> -
Same thing here.

2021-08-13 07:25 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
> +alert( 1 && null && 2 );
```suggestion
alert( 1 && null && 2 );
```

2021-08-13 07:26 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
> -
Same thing here.

2021-08-13 07:27 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> -
Also here. It appears you editor might mess up with new lines. Please restore.

2021-08-13 07:27 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> +alert( alert(1) && alert(2) );
```suggestion
alert( alert(1) && alert(2) );
```

2021-08-13 07:27 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
> -
Also here.

2021-08-13 07:28 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/8-if-question/task.md
> -
Same thing here.

2021-08-13 07:29 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/9-check-login/ifelse_task.svg
> -<svg xmlns="http://www.w3.org/2000/svg" width="599" height="493" viewBox="0 0 599 493"><defs><style>@import url(https://fonts.googleapis.com/css?family=Open+Sans:bold,italic,bolditalic%7CPT+Mono);@fo
I don't see this file is restored. If there is something to translate in this SVG please take a look at the README.md file. You'll find some instructions on how to do that.

2021-08-13 07:31 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +result = a || b
```suggestion
result = a || b;
```

2021-08-13 07:32 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +  alert('Ժամը 12։30֊ն է')
```suggestion
  alert('Ժամը 12։30֊ն է');
```
Only translate strings please and not do any stylistic changes.

2021-08-13 07:32 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +let minute = 30
```suggestion
let hour = 12;
let minute = 30;
```

2021-08-13 07:33 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +  alert('չի երևա, որովհետև արժեքը սխալական է')
```suggestion
  alert('չի երևա, որովհետև արժեքը սխալական է');
```

2021-08-13 07:34 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert(1 && 5) // 5
```suggestion
alert( 1 && 0 ); // 0
alert( 1 && 5 ); // 5
```

2021-08-13 07:35 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert(0 && 'կապ չունի ինչ') // 0
```suggestion
alert( null && 5 ); // null
alert( 0 && "կապ չունի ինչ" ); // 0
```
Please make your it is not your editor altering those examples. Also make sure to restore the original formatting of any example code in all files of this PR. Thank you.

2021-08-13 07:36 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +
Let's get rid of this new line.

2021-08-13 07:37 UTC, bugron commented on 1-js/02-first-steps/11-logical-operators/article.md
> +## ԵՎ "&&"֊ը գտնում է առաջին սխալական արժեքը
Please put this line in its original place.

2021-08-13 07:38 UTC, bugron requested changes
@vahmelk99 please make sure there are no unnecessary line shifts here and there, also make sure to restore original formatting and new lines where mentioned. Thanks for you contribution.

2021-08-13 16:22 UTC, vahmelk99 commented
@bugron thanks for your time.

2021-08-13 16:22 UTC, vahmelk99 commented
/done

2021-08-13 17:40 UTC, bugron commented
@vahmelk99 thanks for your efforts but unfortunately not all the comments are addressed. GitHub might hide some of them so please make sure everything is in order before we can move on to merging this PR. Thanks.

2021-08-13 18:57 UTC, vahmelk99 commented on 1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
> -
![image](https://user-images.githubusercontent.com/30202111/129405856-d4a60ed9-5eb8-432c-b7b4-f189fb83a56e.png)
![image](https://user-images.githubusercontent.com/30202111/129405965-66cf1303-dc0b-4973-94c5-f48b4af2539e.png)

@bugron I don't know why it isn't showing here :/ In my local repo file has 6 lines. And problem not only for this file. There are another files like this.

2021-08-15 07:31 UTC, bugron approved these changes
@vahmelk99 looks superb! Thanks again for your contribution! I've fixed a few line shifts and svg translation stuff and we're ready to merge this PR.

2021-08-15 07:31 UTC, merged

2021-08-15 09:38 UTC, vahmelk99 commented
> @vahmelk99 looks superb! Thanks again for your contribution! I've fixed a few line shifts and svg translation stuff and we're ready to merge this PR.

In the SVG file, I fixed the coordinates of the text, so there were not any overflowed texts.

2021-08-15 14:41 UTC, bugron commented
@vahmelk99 the thing is that SVG file should not be modified directly, there is a note about that in README.md. A special `image.yml` file is used to define SVG text translations and text positions. Cheers.