Conditional branching (Part 1)
javascript-tutorial/hy.javascript.info pull request #91
Opened 2021-11-14 12:42 UTC by ArMinasyan

2022-05-08 21:07 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +Երբեմն, մենք կարիք ենք ունենում կատարել տարբեր գործողություններ, կախված տարբեր պայմաններից։
Երբեմն, մենք կարիք ենք ունենում կատարել տարբեր գործողություններ` կախված տարբեր պայմաններից։

2022-05-08 21:09 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +Դա կատարելու համար, մենք քժկարող ենք օգտագործել `if` գործողույթունը և պայմանական օպերատորը `?`, դա կոչվում է "հարցական նշան"-ի օպերատոր։
Դա կատարելու համար մենք կարող ենք օգտագործել `if` հայտարարությունը և `?` պայմանական օպերատորը, դա նաև կոչվում է «հարցական նշան»-ի օպերատոր։

2022-05-08 21:09 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +## "if" գործողություն
հայտարարություն

2022-05-08 21:14 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +`if(...)` գործողույթունը ստուգում է փակագծերում գրված գրված պայմանը, եթե արդյունքը `true` է, ապա կատարվում է կոդի հատվածը։
հայտարարությունը արժեվորում է պայմանը փակագծերում և, եթե արդյունքը `true` է, ապա կատարում է կոդի հատվածը:

2022-05-08 21:14 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +Օրինակ՝
Օրինակ.

2022-05-08 21:15 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +let year = prompt('Ո՞ր թվականին է ECMAScript-2015 ստանդարտը թողարկվել', '');
Ո՞ր թվականին է ECMAScript-2015 ստանդարտը թողարկվել:

2022-05-08 21:15 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +if (year == 2015) alert( 'Դուք ճիշտ եք' );
Դուք ճիշտ եք:

2022-05-08 21:18 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +Վերը տրված օրինակում, պայմանը ստուգում է պարզ արտահայտությունը (`year == 2015`), բայց դա կարող է լինել ավելի բարդ։
Վերոնշյալ օրինակում պայմանը ստուգում է պարզ հավասարություն  («տարի == 2015»), բայց այն կարող է շատ ավելի բարդ լինել:

2022-05-08 21:29 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +Եթե մենք ցանկանում ենք կատարել մեկից ավել պայմաններ, մենք պետք է գրենք մեր կոդի հատվածները ձևավոր փակագծերի մեջ․
Եթե մենք ցանկանում ենք կատարել մեկից ավել արտահայտություններ, ապա պետք է գրենք մեր կոդի հատվածը ձևավոր փակագծերի ներսում:

2022-05-08 21:36 UTC, galenteryan commented on 1-js/02-first-steps/10-ifelse/article.md
> +Մենք խորհուրդ ենք տալիս տեղադրել կոդի հատվածները `{}`-ի մեջ, ամեն անգամ երբ կրառում եք `if` արտահայտությունը,  նույնիսկ եթե պետք է աշխատի մեկ գործողությւոն։ Դրա կիրառությունը բարձրացնում է ընթեռնելու
Մենք խորհուրդ ենք տալիս պատել կոդի հատվածը ձևավոր փակագծերով `{}` ամեն անգամ, երբ օգտագործում եք `if` արտահայտությունը, նույնիսկ եթե կատարման համար առկա է միայն մեկ գործողություն։ Այդպես բարելավվում է ընթեռնելիությունը:

2022-05-08 21:41 UTC, galenteryan requested changes
Please, correct the translation․

2022-05-09 16:08 UTC, ArMinasyan commented
done

2022-05-09 16:11 UTC, ArMinasyan commented
done

2022-05-10 23:14 UTC, galenteryan commented
Thank you @ArMinasyan!

2022-05-10 23:18 UTC, galenteryan commented
Thank you @ArMinasyan!

Will you continue translating the rest?
If not, I can continue․

2022-05-10 23:20 UTC, galenteryan approved these changes

2022-05-11 04:29 UTC, ArMinasyan commented
I can not

2022-05-11 08:35 UTC, galenteryan commented
> I can not

Ok @ArMinasyan, thank you for your job, it was very helpful.

2022-05-11 19:10 UTC, closed without merging